Feature/new summary
Wavemind/liwi-medal-reader pull request #353
Opened 2021-09-07 12:15 UTC by quentingirard

2021-09-07 12:30 UTC, cini9 approved these changes

2021-09-08 15:10 UTC, cini9 requested changes

2021-09-08 15:10 UTC, cini9 commented on src/Containers/MedicalCase/Summary/SummaryWrapper.js
> +  ///////////////////////////////////////////////////////
☝️ ??

2021-09-08 15:10 UTC, cini9 commented on src/Containers/MedicalCase/Summary/SummaryWrapper.js
> +  ///////////////////////////////////////////////////////
Is this a new notation you are trying out ?

2021-09-08 15:10 UTC, cini9 commented on src/Utils/Date.js
> +  return format(date, 'dd.MM.yyyy')
T''as besoin d'ajouter le locale ?

2021-09-13 08:05 UTC, frescoal requested changes

2021-09-21 13:44 UTC, frescoal approved these changes

2021-09-22 06:36 UTC, merged